/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSmallConstructionRouteImport } from './routes/services.small-construction'
import { Route as ServicesPressureWashingRouteImport } from './routes/services.pressure-washing'
import { Route as ServicesLawnCareRouteImport } from './routes/services.lawn-care'
import { Route as ServicesEngineRepairRouteImport } from './routes/services.engine-repair'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSmallConstructionRoute =
  ServicesSmallConstructionRouteImport.update({
    id: '/services/small-construction',
    path: '/services/small-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPressureWashingRoute = ServicesPressureWashingRouteImport.update({
  id: '/services/pressure-washing',
  path: '/services/pressure-washing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLawnCareRoute = ServicesLawnCareRouteImport.update({
  id: '/services/lawn-care',
  path: '/services/lawn-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEngineRepairRoute = ServicesEngineRepairRouteImport.update({
  id: '/services/engine-repair',
  path: '/services/engine-repair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services/engine-repair': typeof ServicesEngineRepairRoute
  '/services/lawn-care': typeof ServicesLawnCareRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/small-construction': typeof ServicesSmallConstructionRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services/engine-repair': typeof ServicesEngineRepairRoute
  '/services/lawn-care': typeof ServicesLawnCareRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/small-construction': typeof ServicesSmallConstructionRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services/engine-repair': typeof ServicesEngineRepairRoute
  '/services/lawn-care': typeof ServicesLawnCareRoute
  '/services/pressure-washing': typeof ServicesPressureWashingRoute
  '/services/small-construction': typeof ServicesSmallConstructionRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services/engine-repair'
    | '/services/lawn-care'
    | '/services/pressure-washing'
    | '/services/small-construction'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services/engine-repair'
    | '/services/lawn-care'
    | '/services/pressure-washing'
    | '/services/small-construction'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services/engine-repair'
    | '/services/lawn-care'
    | '/services/pressure-washing'
    | '/services/small-construction'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ServicesEngineRepairRoute: typeof ServicesEngineRepairRoute
  ServicesLawnCareRoute: typeof ServicesLawnCareRoute
  ServicesPressureWashingRoute: typeof ServicesPressureWashingRoute
  ServicesSmallConstructionRoute: typeof ServicesSmallConstructionRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/small-construction': {
      id: '/services/small-construction'
      path: '/services/small-construction'
      fullPath: '/services/small-construction'
      preLoaderRoute: typeof ServicesSmallConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pressure-washing': {
      id: '/services/pressure-washing'
      path: '/services/pressure-washing'
      fullPath: '/services/pressure-washing'
      preLoaderRoute: typeof ServicesPressureWashingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lawn-care': {
      id: '/services/lawn-care'
      path: '/services/lawn-care'
      fullPath: '/services/lawn-care'
      preLoaderRoute: typeof ServicesLawnCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/engine-repair': {
      id: '/services/engine-repair'
      path: '/services/engine-repair'
      fullPath: '/services/engine-repair'
      preLoaderRoute: typeof ServicesEngineRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ServicesEngineRepairRoute: ServicesEngineRepairRoute,
  ServicesLawnCareRoute: ServicesLawnCareRoute,
  ServicesPressureWashingRoute: ServicesPressureWashingRoute,
  ServicesSmallConstructionRoute: ServicesSmallConstructionRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
